add_newline = true

[line_break]
disabled = true

[memory_usage]
disabled = false
threshold = 80

[rust]
format = "via [$symbol($numver )]($style)"
disabled = true

[golang]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true

[nix_shell]
format = "$symbol"
symbol = "ïŒ“ "

[git_status]
disabled = true
style = "yellow"
format = "([$conflicted$stashed$staged$deleted$renamed$modified$untracked$ahead_behind]($style) )"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "!$count"
staged = "[+$count](green)"
renamed = "Â»$count"
deleted = "[âœ˜$count](bold red)"

[git_branch]
truncation_length = 20

[python]
format = "[(($virtualenv) )]($style)"
