add_newline = false

[line_break]
disabled = true

[memory_usage]
disabled = false

[git_status]
style = "yellow"
format = '([$conflicted$stashed$staged$deleted$renamed$modified$untracked$ahead_behind]($style) )'
conflicted = "ğŸ³"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = '!$count'
staged = '[+$count](green)'
renamed = "Â»$count"
deleted = "[âœ˜$count](bold red)"

#diverging
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

