add_newline = true

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = 80

[nodejs]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true


[git_status]
disabled = false
style = "yellow"
format = '([$conflicted$stashed$staged$deleted$renamed$modified$untracked$ahead_behind]($style) )' # FIXME: Needs debugging why this affects spacing in terminal
conflicted = "ğŸ³"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = '!$count'
staged = '[+$count](green)'
renamed = "Â»$count"
deleted = "[âœ˜$count](bold red)"

#diverging
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
truncation_length = 20

[python]
python_binary = "python3"
format = 'via [${symbol}(\($virtualenv\) )]($style)'
