add_newline = false

[line_break]
disabled = true

[memory_usage]
disabled = false
threshold = 80

[aws]
disabled = true

[gcloud]
disabled = true


[git_status]
disabled = true #FIXME: Move to chemzoi to facilitate environment differences
style = "yellow"
# format = '([$conflicted$stashed$staged$deleted$renamed$modified$untracked$ahead_behind]($style))' # FIXME: Needs debugging why this affects spacing in terminal
conflicted = "ğŸ³"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = '!$count'
staged = '[+$count](green)'
renamed = "Â»$count"
deleted = "[âœ˜$count](bold red)"

#diverging
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
truncation_length = 20

[python]
python_binary = "python3"
