[tools]
age = "latest"
ast-grep = "latest"
bat = "latest"
bazelisk = "latest"
bottom = "latest"
# btop = "latest"
cloudflared = "latest"
delta = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
glow = "latest"
hyperfine = "latest"
jq = "latest"
k3d = "latest"
k6 = "latest"
k9s = "latest"
kubectl = "latest"
# lazygit = "latest"
mkcert = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tokei = "latest"
yq = "latest"
zoxide = "latest"
bazel-watcher = "latest"
ruff = "latest"
rust = "latest"
go = "latest"
"go:github.com/bazelbuild/buildtools/buildifier" = "latest"
"go:github.com/bazelbuild/buildtools/buildozer" = "latest"
# cmake = "latest"
"cargo:h3i" = "latest"
deno = "latest"
golangci-lint = "latest"
terraform = "latest"
# make = "latest"
zellij = "latest"
tflint = "latest"
terraform-ls = "latest"
node = "latest"
taplo = "latest"
marksman = "latest"
"npm:@vtsls/language-server" = "latest"
pnpm = "latest"
pipx = "latest"
"pipx:isort" = "latest"
"cargo:wasm-pack" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"pipx:pylint" = "latest"
"npm:eslint" = "latest"
"npm:pyright" = "latest"
lua-language-server = "latest"
"npm:yaml-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:prettier" = "latest"
"ubi:fastly/cli"= { version = "latest", exe = "fastly" }
"ubi:bytecodealliance/wasm-tools" = "latest"
usage = "latest"
codex = "latest"

[settings]
experimental = true
